[package]
name = "rust-monster"
version = "0.1.0"
authors = ["El Jacko <eljacko@revolutionsolid.com>", "Ricardo Sisnett <sysnet@revolutionsolid.com>"]

[dependencies]
bitflags = "0.5.0"
log = "0.3.6"
rand = "0.3"

[dev-dependencies]
env_logger = "0.3.2"
